# fly.toml app configuration file generated for finsim on 2026-04-23T00:03:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finsim'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  FINSIM_DATA_DIR = '/data'
  PORT = '8080'

[[mounts]]
  source = 'finsim_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
